### ISSUE TITLE
GenPrimeTable.cpp中的编译错误问题

### ISSUE THREAD

**Issue by bbsy789** [netcan/advanced-cpp20-programming#2]
使用GCC12.2.0进行编译出现缺少头文件错误
https://godbolt.org/z/GPYfqvTWs
使用VS2022 17.4进行编译出现
错误	C2975 “_Size”:“std::array”的模板参数无效，应为编译时常量表达式。

**Comment by bbsy789** [comment]
添加#include <cstdio>后GCC12.2.0编译通过。
https://godbolt.org/z/1nqT69a3M

**Comment by netcan** [comment]
> 添加#include 后GCC12.2.0编译通过。 https://godbolt.org/z/1nqT69a3M

感谢补充，可能这个例子我用clang编译测试的。msvc在19版本测试通过：
https://godbolt.org/z/bc3sn3G5P

msvc在godolt概率性编译失败，提示内存不足，若失败可多试几次

**Comment by bbsy789** [comment]
> 

感谢这么快回复，x64的VS2022，我用起来还是经常出现很奇怪的问题，看起来godolt上的msvc可以编译通过。
